apiVersion: v1

kind: ReplicationController

metadata:

  name: mapper-rc

spec:

  replicas: 3

  selector:

    app: mapper

  template:

    metadata:

      name: mapper-pod

      labels:

        app: mapper

    spec:

      containers:

      - name: mapper

        image: gcr.io/terrycho-sandbox/mapper:v1

        imagePullPolicy: Always

        ports:

        - containerPort: 8080