apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  type: LoadBalancer
  selector:
    app: master
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: master
  labels:
    app: master
spec:
  containers:
  - name: master
    image: gcr.io/psychic-ruler-295605/mapreduce
    ports:
    - containerPort: 8080
      name: mapper
    env:
    - name: TYPE
      value: "MASTER"
    - name: MAPPER_HOST
      value: "mappers"
    - name: REDUCER_HOST
      value: "reducers"
    - name: MAPPER_PORT
      value: "8080"
    - name: REDUCER_PORT
      value: "8080"